# name: CI

# on:
#   push:
#     branches: ["main"]
#     tags: ["v*", "*.*.*"]
#   pull_request:

# jobs:
#   test:
#     name: Test (pytest)
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Install test deps
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest

#       - name: Run tests
#         run: |
#           PYTHONPATH=. pytest -q

#   build_and_push:
#     name: Build & Push to Docker Hub
#     runs-on: ubuntu-latest
#     needs: test
#     if: github.event_name == 'push'
#     env:
#       REGISTRY: docker.io
#       IMAGE_NAME: ${{ secrets.IMAGE_NAME || 'hello-python' }}
#       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Extract metadata (tags, labels)
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
#           tags: |
#             type=sha
#             type=ref,event=branch
#             type=ref,event=tag
#             type=raw,value=latest,enable={{is_default_branch}}

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

name: Use Multi-Builds Python Docker Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call-docker-build:
    uses: michealken30/multi-pipeline-repo/.github/workflows/python-docker-build.yml@main
    with:
      repo: michealken30/CI-DEMO-PYTHON-APP
      path: app
      image_name: michealken30/hello-python:latest
      push: "false"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
